/// Flutter icons HeliosIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HeliosIcons
///      fonts:
///       - asset: fonts/HeliosIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HeliosIcons {
  HeliosIcons._();

  static const _kFontFam = 'HeliosIcons';

  static const IconData home_icon = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData more_icon = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData pricing_icon = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData repertoire_icon = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData pinned_city_icon = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData seat_icon = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData confirm_icon = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData down_arrow_icon = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData duo_seat_icon = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData left_arrow_icon = const IconData(0xe809, fontFamily: _kFontFam);
}
